#!/usr/bin/env python3
"""Generate a self-authored, copyright-clean deep-field sky texture.

Every pixel and source in this asset is procedurally generated by this script.
No external photograph, texture, catalogue, or copyrighted source is used.

The default output is a horizontally seamless 2:1 equirectangular WebP.  Source
positions are sampled on a sphere, diffuse structures use longitude-periodic
noise, and every point-source stamp wraps across the longitude boundary.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
from PIL import Image


DEFAULT_WIDTH = 3072
DEFAULT_HEIGHT = 1536
DEFAULT_SEED = 20260713

STAR_COUNT = 14_500
BRIGHT_STAR_COUNT = 72
ELLIPTICAL_COUNT = 360
SPIRAL_COUNT = 280
HIGH_Z_COUNT = 720


def smoothstep(edge0: float, edge1: float, value: np.ndarray) -> np.ndarray:
    t = np.clip((value - edge0) / (edge1 - edge0), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def periodic_fbm(
    width: int,
    height: int,
    rng: np.random.Generator,
    phase_offset: float,
) -> np.ndarray:
    """Make smooth longitude-periodic noise without storing octave pyramids."""

    longitude = np.linspace(0.0, 2.0 * math.pi, width, endpoint=False, dtype=np.float32)[
        None, :
    ]
    latitude = np.linspace(-math.pi / 2.0, math.pi / 2.0, height, dtype=np.float32)[
        :, None
    ]
    field = np.zeros((height, width), dtype=np.float32)

    amplitudes = (1.0, 0.55, 0.30, 0.16, 0.085)
    for octave, amplitude in enumerate(amplitudes):
        base_frequency = 2**octave
        for _ in range(3):
            # Integer longitude frequencies guarantee a continuous 0/2pi seam.
            k_lon = int(rng.integers(base_frequency, base_frequency * 3 + 1))
            k_lat = float(rng.uniform(0.55, 2.4) * base_frequency)
            if rng.random() < 0.5:
                k_lat *= -1.0
            phase = float(rng.uniform(0.0, 2.0 * math.pi) + phase_offset)
            wave = longitude * k_lon + latitude * k_lat + phase
            np.sin(wave, out=wave)
            field += np.float32(amplitude / 3.0) * wave

    field -= np.float32(field.mean())
    field /= np.float32(max(float(field.std()), 1.0e-6))
    field *= np.float32(0.68)
    np.tanh(field, out=field)
    field *= np.float32(0.5)
    field += np.float32(0.5)

    # Longitude must collapse at the poles on an equirectangular sphere.
    polar_falloff = np.cos(latitude).clip(0.0, 1.0).astype(np.float32) ** np.float32(0.36)
    field -= np.float32(0.5)
    field *= polar_falloff
    field += np.float32(0.5)
    return field


def elliptical_envelope(
    width: int,
    height: int,
    u0: float,
    v0: float,
    sigma_u: float,
    sigma_v: float,
    angle: float,
) -> np.ndarray:
    u = np.linspace(0.0, 1.0, width, endpoint=False, dtype=np.float32)[None, :]
    v = np.linspace(0.0, 1.0, height, dtype=np.float32)[:, None]
    du = np.mod(u - np.float32(u0) + np.float32(0.5), np.float32(1.0)) - np.float32(
        0.5
    )
    # Correct local longitude scale at the envelope latitude.
    du *= np.float32(max(math.cos((v0 - 0.5) * math.pi), 0.20))
    dv = v - np.float32(v0)
    c = np.float32(math.cos(angle))
    s = np.float32(math.sin(angle))
    xr = du * c + dv * s
    yr = -du * s + dv * c
    radius2 = (xr / np.float32(sigma_u)) ** 2 + (yr / np.float32(sigma_v)) ** 2
    radius2 *= np.float32(-0.5)
    np.exp(radius2, out=radius2)
    return radius2


def add_patch_wrap(canvas: np.ndarray, patch: np.ndarray, center_x: int, center_y: int) -> None:
    """Add an RGB patch, wrapping in longitude and clipping at the poles."""

    canvas_height, canvas_width, _ = canvas.shape
    patch_height, patch_width, _ = patch.shape
    x0 = center_x - patch_width // 2
    y0 = center_y - patch_height // 2

    dst_y0 = max(0, y0)
    dst_y1 = min(canvas_height, y0 + patch_height)
    if dst_y0 >= dst_y1:
        return
    src_y0 = dst_y0 - y0
    src_y1 = src_y0 + (dst_y1 - dst_y0)

    for wrap_shift in (-canvas_width, 0, canvas_width):
        shifted_x0 = x0 + wrap_shift
        dst_x0 = max(0, shifted_x0)
        dst_x1 = min(canvas_width, shifted_x0 + patch_width)
        if dst_x0 >= dst_x1:
            continue
        src_x0 = dst_x0 - shifted_x0
        src_x1 = src_x0 + (dst_x1 - dst_x0)
        canvas[dst_y0:dst_y1, dst_x0:dst_x1] += patch[
            src_y0:src_y1, src_x0:src_x1
        ]


def source_position(
    rng: np.random.Generator,
    clusters: np.ndarray | None = None,
    cluster_probability: float = 0.0,
) -> tuple[float, float]:
    if clusters is not None and rng.random() < cluster_probability:
        center = clusters[int(rng.integers(0, len(clusters)))]
        u = float((center[0] + rng.normal(0.0, center[2])) % 1.0)
        v = float(np.clip(center[1] + rng.normal(0.0, center[3]), 0.075, 0.925))
        return u, v

    # Uniform solid-angle sampling, with a small polar guard for finite stamps.
    z = float(rng.uniform(-0.975, 0.975))
    u = float(rng.random())
    v = 0.5 + math.asin(z) / math.pi
    return u, v


def pixel_position(u: float, v: float, width: int, height: int) -> tuple[int, int, float]:
    x = int(round((u % 1.0) * width)) % width
    y = int(round(np.clip(v, 0.0, 1.0) * (height - 1)))
    latitude = (v - 0.5) * math.pi
    x_stretch = 1.0 / max(math.cos(latitude), 0.35)
    return x, y, x_stretch


def star_color(rng: np.random.Generator) -> np.ndarray:
    selector = float(rng.random())
    if selector < 0.46:
        warm = float(rng.uniform(0.0, 1.0))
        return np.array([1.0, 0.72 + 0.16 * warm, 0.52 + 0.25 * warm], np.float32)
    if selector < 0.87:
        neutral = float(rng.uniform(0.0, 1.0))
        return np.array([0.92 + 0.08 * neutral, 0.91 + 0.07 * neutral, 0.86], np.float32)
    blue = float(rng.uniform(0.0, 1.0))
    return np.array([0.62 + 0.20 * blue, 0.78 + 0.16 * blue, 1.0], np.float32)


def gaussian_star_kernel(radius: int) -> np.ndarray:
    coordinates = np.arange(-radius, radius + 1, dtype=np.float32)
    xx, yy = np.meshgrid(coordinates, coordinates)
    sigma = np.float32(0.48 + 0.22 * radius)
    kernel = np.exp(-(xx * xx + yy * yy) / (2.0 * sigma * sigma)).astype(np.float32)
    if radius >= 2:
        halo_sigma = np.float32(radius * 0.95)
        kernel += np.float32(0.055) * np.exp(
            -(xx * xx + yy * yy) / (2.0 * halo_sigma * halo_sigma)
        ).astype(np.float32)
    return kernel


def bright_star_stamp(radius: int, brightness: float, color: np.ndarray) -> np.ndarray:
    half_size = radius * 3
    coordinates = np.arange(-half_size, half_size + 1, dtype=np.float32)
    xx, yy = np.meshgrid(coordinates, coordinates)
    rr2 = xx * xx + yy * yy
    core = np.exp(-rr2 / np.float32(0.62**2 * 2.0))
    halo = np.float32(0.045) * np.exp(
        -rr2 / np.float32(max(radius * 0.82, 1.0) ** 2 * 2.0)
    )
    spike_length = np.float32(max(radius * 1.45, 2.0))
    horizontal = np.exp(-np.abs(yy) / np.float32(0.30)) * np.exp(
        -np.abs(xx) / spike_length
    )
    vertical = np.exp(-np.abs(xx) / np.float32(0.30)) * np.exp(
        -np.abs(yy) / spike_length
    )
    diagonal_a = np.exp(-np.abs(xx - yy) / np.float32(0.45)) * np.exp(
        -(np.abs(xx) + np.abs(yy)) / (spike_length * np.float32(1.35))
    )
    diagonal_b = np.exp(-np.abs(xx + yy) / np.float32(0.45)) * np.exp(
        -(np.abs(xx) + np.abs(yy)) / (spike_length * np.float32(1.35))
    )
    intensity = core + halo + np.float32(0.050) * (horizontal + vertical)
    intensity += np.float32(0.022) * (diagonal_a + diagonal_b)
    return intensity[..., None].astype(np.float32) * color[None, None, :] * np.float32(
        brightness
    )


def rotated_coordinates(
    radius: float,
    x_stretch: float,
    angle: float,
    extent: float = 3.0,
) -> tuple[np.ndarray, np.ndarray]:
    half_x = max(2, int(math.ceil(radius * extent * x_stretch)))
    half_y = max(2, int(math.ceil(radius * extent)))
    xx = np.arange(-half_x, half_x + 1, dtype=np.float32) / np.float32(
        max(radius * x_stretch, 0.5)
    )
    yy = np.arange(-half_y, half_y + 1, dtype=np.float32) / np.float32(max(radius, 0.5))
    x_grid, y_grid = np.meshgrid(xx, yy)
    c = np.float32(math.cos(angle))
    s = np.float32(math.sin(angle))
    return x_grid * c + y_grid * s, -x_grid * s + y_grid * c


def elliptical_galaxy_stamp(
    radius: float,
    x_stretch: float,
    axis_ratio: float,
    angle: float,
    brightness: float,
    color_bias: float,
) -> np.ndarray:
    x_rot, y_rot = rotated_coordinates(radius, x_stretch, angle)
    elliptical_radius = np.sqrt(x_rot * x_rot + (y_rot / np.float32(axis_ratio)) ** 2)
    profile = np.float32(0.70) * np.exp(
        -np.float32(3.15) * np.sqrt(np.maximum(elliptical_radius, 0.0))
    )
    profile += np.float32(0.30) * np.exp(-np.float32(1.38) * elliptical_radius)
    cutoff = np.float32(1.0) - smoothstep(2.05, 3.0, elliptical_radius)
    profile *= cutoff
    profile *= np.float32(0.94) + np.float32(0.06) * np.cos(
        np.float32(7.0) * np.arctan2(y_rot, x_rot) + np.float32(3.3) * elliptical_radius
    )

    core_color = np.array([1.0, 0.79, 0.52], dtype=np.float32)
    outer_color = np.array(
        [0.86 + 0.10 * color_bias, 0.35 + 0.20 * color_bias, 0.22], dtype=np.float32
    )
    mix_value = np.clip(elliptical_radius / np.float32(2.2), 0.0, 1.0)[..., None]
    color = core_color[None, None, :] * (np.float32(1.0) - mix_value)
    color += outer_color[None, None, :] * mix_value
    return profile[..., None].astype(np.float32) * color * np.float32(brightness)


def spiral_galaxy_stamp(
    radius: float,
    x_stretch: float,
    axis_ratio: float,
    angle: float,
    brightness: float,
    arms: int,
    winding: float,
    phase: float,
) -> np.ndarray:
    x_rot, y_rot = rotated_coordinates(radius, x_stretch, angle, extent=3.1)
    plane_y = y_rot / np.float32(axis_ratio)
    radial = np.sqrt(x_rot * x_rot + plane_y * plane_y)
    azimuth = np.arctan2(plane_y, x_rot)
    arm_phase = np.float32(arms) * (
        azimuth + np.float32(winding) * np.log(radial + np.float32(0.075))
    ) + np.float32(phase)
    arm_ridge = np.float32(0.5) + np.float32(0.5) * np.cos(arm_phase)
    arm_ridge = arm_ridge**np.float32(7.0)

    disk = np.exp(-np.float32(1.72) * radial)
    disk *= np.float32(1.0) - smoothstep(2.25, 3.0, radial)
    arm_mask = disk * arm_ridge * smoothstep(0.10, 0.42, radial)
    bulge = np.exp(-np.float32(4.6) * np.sqrt(np.maximum(radial, 0.0)))
    old_disk = disk * (np.float32(0.12) + np.float32(0.14) * np.cos(arm_phase * 0.5) ** 2)

    # A narrow absorption lane makes highly inclined systems read as edge-on.
    dust_lane = np.exp(-(y_rot / np.float32(0.085 + 0.10 * axis_ratio)) ** 2)
    lane_strength = np.float32(np.clip((0.48 - axis_ratio) * 1.25, 0.0, 0.58))
    arm_mask *= np.float32(1.0) - lane_strength * dust_lane
    old_disk *= np.float32(1.0) - lane_strength * dust_lane

    warm = np.array([1.0, 0.66, 0.32], dtype=np.float32)
    blue = np.array([0.32, 0.61, 1.0], dtype=np.float32)
    old = np.array([0.84, 0.46, 0.24], dtype=np.float32)
    patch = bulge[..., None] * warm[None, None, :] * np.float32(1.18)
    patch += arm_mask[..., None] * blue[None, None, :] * np.float32(1.42)
    patch += old_disk[..., None] * old[None, None, :]
    return patch.astype(np.float32) * np.float32(brightness)


def high_z_galaxy_stamp(
    radius: float,
    x_stretch: float,
    axis_ratio: float,
    angle: float,
    brightness: float,
    color: np.ndarray,
    clump_phase: float,
) -> np.ndarray:
    x_rot, y_rot = rotated_coordinates(radius, x_stretch, angle, extent=2.8)
    radial2 = x_rot * x_rot + (y_rot / np.float32(axis_ratio)) ** 2
    body = np.exp(-np.float32(2.25) * radial2)
    offset_x = np.float32(0.32 * math.cos(clump_phase))
    offset_y = np.float32(0.22 * math.sin(clump_phase))
    clump = np.exp(
        -np.float32(7.0)
        * ((x_rot - offset_x) ** 2 + ((y_rot - offset_y) / np.float32(axis_ratio)) ** 2)
    )
    halo = np.float32(0.15) * np.exp(-np.float32(1.15) * np.sqrt(radial2))
    intensity = body + np.float32(0.42) * clump + halo
    intensity *= np.float32(1.0) - smoothstep(1.85, 2.75, np.sqrt(radial2))
    return intensity[..., None].astype(np.float32) * color[None, None, :] * np.float32(
        brightness
    )


def build_sky(width: int, height: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    radiance = np.empty((height, width, 3), dtype=np.float32)
    radiance[..., 0] = np.float32(7.0e-6)
    radiance[..., 1] = np.float32(10.0e-6)
    radiance[..., 2] = np.float32(17.0e-6)

    broad_noise = periodic_fbm(width, height, rng, 0.0)
    fine_noise = periodic_fbm(width, height, rng, 1.973)
    centered_noise = broad_noise - np.float32(0.5)
    radiance[..., 0] += centered_noise * np.float32(8.0e-6)
    radiance[..., 1] += centered_noise * np.float32(13.0e-6)
    radiance[..., 2] += centered_noise * np.float32(24.0e-6)

    # Localized emission complexes: visible under exposure, but never a grey all-sky veil.
    nebulae = (
        (0.655, 0.305, 0.165, 0.052, 0.34, (0.12, 0.24, 0.62), 0.0041),
        (0.378, 0.695, 0.145, 0.046, -0.48, (0.48, 0.10, 0.31), 0.0031),
        (0.905, 0.585, 0.115, 0.036, 0.18, (0.56, 0.22, 0.075), 0.0026),
    )
    filament = np.clip((fine_noise - np.float32(0.43)) * np.float32(2.9), 0.0, 1.0)
    filament *= filament
    for u0, v0, sigma_u, sigma_v, angle, color, strength in nebulae:
        envelope = elliptical_envelope(width, height, u0, v0, sigma_u, sigma_v, angle)
        mask = envelope * (np.float32(0.09) + np.float32(0.91) * filament)
        mask *= np.float32(0.64) + np.float32(0.36) * broad_noise
        for channel, component in enumerate(color):
            radiance[..., channel] += mask * np.float32(strength * component)

        dust = np.clip((broad_noise - np.float32(0.56)) * np.float32(3.4), 0.0, 1.0)
        attenuation = np.float32(1.0) - envelope * dust * np.float32(0.44)
        for channel in range(3):
            radiance[..., channel] *= attenuation

    del broad_noise, centered_noise, filament

    # Sparse stars: predominantly sub-pixel, plus a small Hubble-like diffraction population.
    star_kernels = {radius: gaussian_star_kernel(radius) for radius in (1, 2, 3)}
    for _ in range(STAR_COUNT):
        u, v = source_position(rng)
        x, y, _ = pixel_position(u, v, width, height)
        brightness = 0.00125 + 0.065 * float(rng.random()) ** 6.2
        radius = 1 if brightness < 0.006 else (2 if brightness < 0.025 else 3)
        color = star_color(rng)
        patch = star_kernels[radius][..., None] * color[None, None, :] * np.float32(
            brightness
        )
        add_patch_wrap(radiance, patch.astype(np.float32), x, y)

    for _ in range(BRIGHT_STAR_COUNT):
        u, v = source_position(rng)
        x, y, _ = pixel_position(u, v, width, height)
        radius = int(rng.integers(3, 8))
        brightness = float(rng.uniform(0.18, 0.86) * (1.0 + rng.random() ** 5))
        add_patch_wrap(radiance, bright_star_stamp(radius, brightness, star_color(rng)), x, y)

    # Mild clustering gives the deep field structure without a synthetic regular distribution.
    clusters = np.column_stack(
        (
            rng.random(18),
            rng.uniform(0.12, 0.88, 18),
            rng.uniform(0.010, 0.036, 18),
            rng.uniform(0.009, 0.028, 18),
        )
    ).astype(np.float32)

    for _ in range(ELLIPTICAL_COUNT):
        u, v = source_position(rng, clusters, 0.43)
        x, y, x_stretch = pixel_position(u, v, width, height)
        radius = float(np.clip(1.55 + rng.pareto(2.7) * 1.35, 1.55, 9.5))
        axis_ratio = float(rng.uniform(0.42, 1.0))
        angle = float(rng.uniform(0.0, math.pi))
        brightness = float(rng.uniform(0.016, 0.074) * (1.0 + rng.random() ** 4 * 2.2))
        patch = elliptical_galaxy_stamp(
            radius, x_stretch, axis_ratio, angle, brightness, float(rng.random())
        )
        add_patch_wrap(radiance, patch, x, y)

    for _ in range(SPIRAL_COUNT):
        u, v = source_position(rng, clusters, 0.48)
        x, y, x_stretch = pixel_position(u, v, width, height)
        radius = float(np.clip(2.4 + rng.pareto(3.0) * 2.0, 2.4, 11.5))
        axis_ratio = float(rng.uniform(0.27, 0.94))
        angle = float(rng.uniform(0.0, math.pi))
        brightness = float(rng.uniform(0.018, 0.082) * (1.0 + rng.random() ** 4 * 2.0))
        patch = spiral_galaxy_stamp(
            radius,
            x_stretch,
            axis_ratio,
            angle,
            brightness,
            int(rng.choice((2, 2, 2, 3, 4))),
            float(rng.uniform(1.35, 2.75)),
            float(rng.uniform(0.0, 2.0 * math.pi)),
        )
        add_patch_wrap(radiance, patch, x, y)

    high_z_palette = np.array(
        (
            (1.00, 0.27, 0.12),
            (1.00, 0.43, 0.18),
            (0.92, 0.25, 0.35),
            (0.80, 0.34, 0.18),
            (0.74, 0.27, 0.45),
        ),
        dtype=np.float32,
    )
    for _ in range(HIGH_Z_COUNT):
        u, v = source_position(rng, clusters, 0.58)
        x, y, x_stretch = pixel_position(u, v, width, height)
        radius = float(rng.uniform(0.82, 2.65) * (1.0 + 0.75 * rng.random() ** 7))
        axis_ratio = float(rng.uniform(0.38, 0.94))
        angle = float(rng.uniform(0.0, math.pi))
        brightness = float(rng.uniform(0.010, 0.055) * (1.0 + rng.random() ** 5 * 1.8))
        color = high_z_palette[int(rng.integers(0, len(high_z_palette)))]
        patch = high_z_galaxy_stamp(
            radius,
            x_stretch,
            axis_ratio,
            angle,
            brightness,
            color,
            float(rng.uniform(0.0, 2.0 * math.pi)),
        )
        add_patch_wrap(radiance, patch, x, y)

    # A recognizable group close to the simulator's initial lensed direction.
    signatures: tuple[tuple[str, tuple[float, ...]], ...] = (
        ("spiral", (0.087, 0.426, 25.0, 0.84, -0.34, 0.60, 2.0, 2.20, 0.45)),
        ("elliptical", (0.069, 0.444, 16.0, 0.66, 0.52, 0.48, 0.72)),
        ("spiral", (0.112, 0.438, 23.0, 0.22, 0.10, 0.58, 2.0, 1.55, 2.15)),
        ("spiral", (0.102, 0.407, 12.0, 0.72, 0.72, 0.42, 3.0, 2.45, 1.40)),
        ("elliptical", (0.096, 0.456, 8.5, 0.78, -0.65, 0.38, 0.24)),
        ("highz", (0.078, 0.413, 5.3, 0.58, 0.62, 0.27, 3.75)),
    )
    for kind, values in signatures:
        u, v = values[0], values[1]
        x, y, x_stretch = pixel_position(u, v, width, height)
        if kind == "spiral":
            _, _, radius, axis_ratio, angle, brightness, arms, winding, phase = values
            patch = spiral_galaxy_stamp(
                radius,
                x_stretch,
                axis_ratio,
                angle,
                brightness,
                int(arms),
                winding,
                phase,
            )
        elif kind == "elliptical":
            _, _, radius, axis_ratio, angle, brightness, color_bias = values
            patch = elliptical_galaxy_stamp(
                radius, x_stretch, axis_ratio, angle, brightness, color_bias
            )
        else:
            _, _, radius, axis_ratio, angle, brightness, clump_phase = values
            patch = high_z_galaxy_stamp(
                radius,
                x_stretch,
                axis_ratio,
                angle,
                brightness,
                np.array([1.0, 0.30, 0.15], dtype=np.float32),
                clump_phase,
            )
        add_patch_wrap(radiance, patch, x, y)

    del fine_noise

    # Linear radiance -> restrained filmic response -> sRGB-like gamma.
    np.maximum(radiance, np.float32(0.0), out=radiance)
    radiance *= np.float32(1.20)
    radiance *= np.float32(-1.0)
    np.exp(radiance, out=radiance)
    radiance *= np.float32(-1.0)
    radiance += np.float32(1.0)
    np.clip(radiance, 0.0, 1.0, out=radiance)
    np.power(radiance, np.float32(1.0 / 2.2), out=radiance)
    image = np.clip(radiance * np.float32(255.0) + np.float32(0.5), 0.0, 255.0).astype(
        np.uint8
    )

    # Collapse longitude at the two poles and make the stored seam exact.
    for row in range(4):
        blend = np.float32((4 - row) / 4.0)
        north_mean = image[row].mean(axis=0, dtype=np.float64).astype(np.float32)
        south_mean = image[-1 - row].mean(axis=0, dtype=np.float64).astype(np.float32)
        image[row] = np.clip(
            image[row].astype(np.float32) * (1.0 - blend) + north_mean * blend,
            0.0,
            255.0,
        ).astype(np.uint8)
        image[-1 - row] = np.clip(
            image[-1 - row].astype(np.float32) * (1.0 - blend) + south_mean * blend,
            0.0,
            255.0,
        ).astype(np.uint8)
    seam_average = (
        image[:, 0].astype(np.uint16) + image[:, -1].astype(np.uint16) + np.uint16(1)
    ) // np.uint16(2)
    image[:, 0] = seam_average.astype(np.uint8)
    image[:, -1] = seam_average.astype(np.uint8)
    return image


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "assets" / "deep-field.webp",
    )
    parser.add_argument("--width", type=int, default=DEFAULT_WIDTH)
    parser.add_argument("--height", type=int, default=DEFAULT_HEIGHT)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.width < 3072 or args.height < 1536:
        raise SystemExit("width and height must be at least 3072x1536")
    if args.width != args.height * 2:
        raise SystemExit("an equirectangular sky must use an exact 2:1 aspect ratio")

    pixels = build_sky(args.width, args.height, args.seed)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(pixels, mode="RGB").save(
        args.output,
        format="WEBP",
        lossless=True,
        quality=100,
        method=6,
        exact=True,
    )
    with Image.open(args.output) as encoded_image:
        encoded_pixels = np.asarray(encoded_image.convert("RGB"))
    seam_error = float(
        np.abs(
            encoded_pixels[:, 0].astype(np.int16)
            - encoded_pixels[:, -1].astype(np.int16)
        ).mean()
    )
    print(f"wrote {args.output}")
    print(f"size: {args.width}x{args.height}, seed: {args.seed}, seam MAE: {seam_error:.3f}")
    print(
        "sources: "
        f"{STAR_COUNT + BRIGHT_STAR_COUNT} stars, "
        f"{ELLIPTICAL_COUNT} elliptical, {SPIRAL_COUNT} spiral, "
        f"{HIGH_Z_COUNT} high-z galaxies, plus 6 signature galaxies"
    )


if __name__ == "__main__":
    main()
